### ISSUE TITLE
Word vectors are 'nan's when training Chinese corpus with CBOW and multiprocessing mode

### ISSUE THREAD

**Issue by innerfirexy** [ray1007/pytorch-word2vec#3]
Hi Tzu-Ray,

Here I am again :-) 
This time I tested with a small Chinese dataset (from Wikipedia dump) and found that when running main.py with --cbow=1, the resulting word vectors were all "nan"s, like:
```
的      nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan           nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan     nan 
```

Training the same data with main_simple.py is no problem.
Also, training using --cbow=0 with either main.py or main_simple.py is OK.

I quickly tested with text8 and found that English data does not have this "nan" vector issue.

Yang

**Comment by ray1007** [comment]
Hi Yang,

I observed the same thing before. I made multiple repetitions, and it seems to be a heisenbug in multiprocessing mode. (`main.py`) I believe if you repeat more times, nan will eventually show up when using text8. :( 

At this moment I am still looking for the culprit, I'll reply with my new findings once I have it. And please feel free to contact me if you have some ideas about the bug, or this repo!

Tzu-Ray

**Comment by innerfirexy** [comment]
I reinstalled the newest pytorch from source and I captured the following error running main.py with --cbow=1 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yangxu/GitHub/my-pytorch-word2vec/pytorch-word2vec/main.py", line 327, in train_process
    loss = model(data)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yangxu/GitHub/my-pytorch-word2vec/pytorch-word2vec/main.py", line 129, in forward
    neg_loss = torch.sum( -F.logsigmoid(-neg_ips)  )
RuntimeError: value cannot be converted to type float without overflow: 415031034115965960531206270556076769280.000000
```
Seems that this is a way too large number for F.logsigmoid. 
When I tried compute this number using F.logsigmoid in iPython, it returns a "nan", and I guess that's why the embedding matrix is written with "nan"s before.
The interesting thing is: each time I ran main.py, the program ran for a while and then 3 processes died (I used the default number of processes 4), and the rest one process kept running until done. But the resulting embeddings written to vector.txt were wrong (all very large float numbers).

I tried Python's native multiprocessing instead of torch's wrapper, and it gave the same error.

Again, I did not capture this overflow error using main.py with --cbow=0 (Skipgram).

Hope this information will help!
Yang

**Comment by ray1007** [comment]
Thanks for the information Yang! It's really helpful!
I made a new commit, and tested `main.py` on another machine. On my machine I did not see NaN in multiple runs. Let see if it get rids of the bug on your side! 

Below are some workarounds I tried for the problems in `F.logsigmoid`.
After doing some math, the gradient we need is shown in the first figure, where `d` is the inner product of two vectors, `σ` is sigmoid function, `logit` is the output of sigmoid, and `t` is the target. 
![default](https://user-images.githubusercontent.com/7671322/32811833-b767c996-c9dc-11e7-91da-cedfc8661dc4.png)

As long as the gradient of loss w.r.t d (inner products) is `-(t-logit)`, the program should work normally. So I defined a custom `torch.autograd.Function` called `MySigmoid`, where I could control the forward and backward function. I set the forward to be a sigmoid function, and backward to be identity. With MSE as my loss function (instead of negative log likelihood), the computational graph runs as shown below.
![default](https://user-images.githubusercontent.com/7671322/32811853-d198cd6a-c9dc-11e7-9cc8-3f6fcd5b0857.png)

Tzu-Ray

**Comment by innerfirexy** [comment]
Hi Tzu-Ray,
Thanks for the prompt fix! I quickly tested on two Mac machines. This time, the overflow problem is gone, but the "nan"s are still there in the output vector files. 
What OS did you test your code, Linux or Mac?
Yang

**Comment by ray1007** [comment]
Hi Yang, 
I tested my code on Linux. Too bad to hear that. :P
BTW right now I'm trying to clamp the inner product between [-10,10] before feeding it to `F.logsigmoid`. I made a new commit, and I hope it fixes the NaN problem under limited numerical range this time. :)
Please let me know your results !

Tzu-Ray

**Comment by innerfirexy** [comment]
Aha! The clamping solves the issue!! I'm gonna test on a larger dataset tomorrow.
Thanks again!

Yang

**Comment by ray1007** [comment]
Great to hear that! :)

Tzu-Ray
